### ISSUE TITLE
Generate not working

### ISSUE THREAD

**Issue by buckhornmktg** [TiagoSilvaPereira/vemto-releases#1]
Mac installs php 7.1 in /usr/bin and even though I updated the $PATH variable to use /usr/local/bin, Vemto grabs the system php, not my homebrew php 7.4 version. When I try to "run" the correct PHP version is used from the home screen settings. It seems "generate" does not use that variable to find the correct php version.

Unhandled Promise Rejection
Error: Command failed: /usr/local/bin/composer install
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires php ^7.3|^8.0 but your php version (7.1.23) does not satisfy that requirement.
  Problem 2
    - laravel/framework[v8.12.0, ..., 8.x-dev] require php ^7.3|^8.0 -> your php version (7.1.23) does not satisfy that requirement.
    - Root composer.json requires laravel/framework ^8.12 -> satisfiable by laravel/framework[v8.12.0, ..., 8.x-dev].
    at electron/js2c/asar.js:727:23
    at o.executeCommand (app://./js/chunk-common.91b0686d.js:1:24749)
    at Le.runComposer (app://./js/generator.3044fac6.js:1:28661)
    at app://./js/generator.3044fac6.js:1:28389
    at new Promise (<anonymous>)
    at Le.runCommands (app://./js/generator.3044fac6.js:1:28360)
    at Le.start (app://./js/generator.3044fac6.js:1:28325)
    at gt.callProjectGenerators (app://./js/generator.3044fac6.js:1:34533)

**Comment by TiagoSilvaPereira** [comment]
Hi @buckhornmktg we fixed this issue on Vemto 0.5.5 launched today. For future issues, please use the vemto-issues repository. Have a nice day, thank you
