### ISSUE TITLE
Run doesn't find NPM

### ISSUE THREAD

**Issue by buckhornmktg** [TiagoSilvaPereira/vemto-releases#2]
When I try to "run" I get an error saying NPM isn't found. I have set the path entered on the home screen settings and can even run the command that Vemto says isn't found.... /usr/local/bin/npm -v returns the NPM version.

**Comment by TiagoSilvaPereira** [comment]
Hi @buckhornmktg we fixed this issue on Vemto 0.5.5 launched today. For future issues, please use the vemto-issues repository. Have a nice day, thank you
