### ISSUE TITLE
Can't edit crud

### ISSUE THREAD

**Issue by buckhornmktg** [TiagoSilvaPereira/vemto-releases#3]
![image](https://user-images.githubusercontent.com/13803036/97819013-c7397d00-1c5a-11eb-9499-3940ac7dd0a7.png)
On windows 10 virtual box (couldn't get this to run on my mac, because system php is used, not php version I'm specifying in $PATH or the app settings).

Crud options overflows off the screen with no scrolling or drag support so I'm unable to edit. Maybe it's a misunderstanding of how the app works. Should I only be developing just a few models at a time, publishing and then removing from the generator? Or should I develop the entire app and then publish?

**Comment by TiagoSilvaPereira** [comment]
Hi @buckhornmktg thank you for reporting, It is a bug, I'll change this screen to fit all CRUD in the screen for next Vemto version. Have a nice day, cheers. (I'm closing here to open the issue in the correct vemto-issues repository :pray: )
